<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="rooster" params="name simulation:=false
                                           camera_front:=false
                                           camera_rear:=false
                                           lidar:=true">

    <!-- Included xacros -->
    <xacro:include filename="$(find jackal_description_cdt)/urdf/lidar/base_lidar.xacro"/>

    <!-- Properties -->
    <xacro:property name="cylinder_height" value="0.30" />
    <xacro:property name="cylinder_radius" value="0.04" />

    <link name="${name}">
      <visual>
        <geometry>
        <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
        <material name="white">
          <color rgba="0.5 0.5 .5 1"/>
        </material>
      </visual>
    </link>

    <joint name="box_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="0.15 0.0 ${cylinder_height/2}" rpy="0 0 0"/>
    </joint>
    

    <!-- LIDAR -->
    <xacro:if value="${lidar}">
      <xacro:base_lidar name="horizontal"
                        parent="${name}"
                        max_range="5"
                        min_range="0.1"
                        translateX="0"
                        translateY="0"
                        translateZ="${cylinder_height/2}"
                        roll="0"
                        pitch="0"
                        yaw="-${PI/2}"
                        simulation="${simulation}">
                        <cylinder length="0.0005" radius="0.023"/>
                        <!-- yaw was 0 mfallon. now facing forward-->
      </xacro:base_lidar>
    </xacro:if>


  </xacro:macro>
</robot>
